server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      # uri: mongodb+srv://admin:codedecode@atlas-cluster.mqdj7js.mongodb.net/?retryWrites=true&w=majority
      mongodb: //localhost:27017/orderdb
      #host: atlas-cluster.mqdj7js.mongodb.net
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        enabled: true


